GET http://localhost:8080/v1/users

###
POST http://localhost:8080/v1/user
content-type: application/json

# 
{
    "name": "name",
    "email": "email"
}

###
DELETE  http://localhost:8080/v1/user
content-type: application/json

{
    "email": "email"
}


###
GET  http://localhost:8080/v1/health_check

### 
GET  http://localhost:8080/v1

### 
PUT  http://localhost:8080/v1/user
content-type: application/json

{
    "name": "name",
    "email": "email"
}